<?php
declare(strict_types=1);
session_start();
$photoAccess = ($_SESSION['emilia_photo_access'] ?? false) === true;
$returnTo = rawurlencode($_SERVER['REQUEST_URI']);
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Emilia’s Albums — La Davina Emilia</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"></head>
<body class="journal-page"><header class="survey-header"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">✦</span><span>La Davina Emilia</span></a><span>Her albums</span></header><main class="album-page-shell"><section class="album-page-intro"><p class="eyebrow">Emilia’s albums</p><h1>Every place is more beautiful when she <em>arrives.</em></h1><p>Private glimpses from the world she has made entirely her own.</p><?php if (!$photoAccess): ?><a class="button button-primary" href="/gate.php?return=<?= $returnTo ?>">Enter the gallery</a><?php endif; ?></section>
<nav class="journal-nav album-nav" aria-label="Album collections"><a href="#after-dark">After dark</a><a href="#on-the-move">On the move</a><a href="#salt-and-sun">Salt &amp; sun</a></nav>
<section class="album-collection" id="after-dark"><header><p class="eyebrow">Album I</p><h2>After <em>dark.</em></h2><p>Late tables, low light, and the kind of evening that remembers her.</p></header><div class="album-page-grid after-dark-grid"><figure class="album-page-photo album-page-tall personal-photo"><?php if ($photoAccess): ?><img src="/image.php?id=hero" alt="La Davina Emilia in a sparkling top at dinner"><?php else: ?><a class="private-photo-gate" href="/gate.php?return=<?= $returnTo ?>"><span aria-hidden="true">✦</span><strong>A private glimpse</strong><small>Enter Emilia’s word to look closer</small></a><?php endif; ?><figcaption>She arrives. The room adjusts.</figcaption></figure><figure class="album-page-photo personal-photo"><?php if ($photoAccess): ?><img src="/image.php?id=table" alt="La Davina Emilia at a table with champagne"><?php else: ?><a class="private-photo-gate" href="/gate.php?return=<?= $returnTo ?>"><span aria-hidden="true">✦</span><strong>A beautiful evening</strong><small>Enter Emilia’s word to look closer</small></a><?php endif; ?><figcaption>The table was waiting.</figcaption></figure></div></section>
<section class="album-collection" id="on-the-move"><header><p class="eyebrow">Album II</p><h2>On the <em>move.</em></h2><p>Somewhere worth arriving for—and always on her own terms.</p></header><div class="album-page-grid on-the-move-grid"><figure class="album-page-photo personal-photo"><?php if ($photoAccess): ?><img src="/image.php?id=travel" alt="La Davina Emilia in the city at dusk"><?php else: ?><a class="private-photo-gate" href="/gate.php?return=<?= $returnTo ?>"><span aria-hidden="true">✦</span><strong>Travel portrait</strong><small>Enter Emilia’s word to look closer</small></a><?php endif; ?><figcaption>Somewhere worth arriving for.</figcaption></figure><figure class="album-page-photo album-page-wide personal-photo"><?php if ($photoAccess): ?><img src="/image.php?id=boat" alt="La Davina Emilia on a boat"><?php else: ?><a class="private-photo-gate" href="/gate.php?return=<?= $returnTo ?>"><span aria-hidden="true">✦</span><strong>An adventure begins</strong><small>Enter Emilia’s word to look closer</small></a><?php endif; ?><figcaption>She always knows the way.</figcaption></figure></div></section>
<section class="album-collection" id="salt-and-sun"><header><p class="eyebrow">Album III</p><h2>Salt &amp; <em>sun.</em></h2><p>A little proof that the horizon knows exactly who it belongs to.</p></header><div class="album-page-grid salt-and-sun-grid"><figure class="album-page-photo album-page-solo personal-photo"><?php if ($photoAccess): ?><img src="/image.php?id=about" alt="La Davina Emilia by the water"><?php else: ?><a class="private-photo-gate" href="/gate.php?return=<?= $returnTo ?>"><span aria-hidden="true">✦</span><strong>Portrait in her element</strong><small>Enter Emilia’s word to look closer</small></a><?php endif; ?><figcaption>In her element.</figcaption></figure></div></section>
</main></body></html>
