<?php
declare(strict_types=1);
session_start();
if (($_SESSION['emilia_art_access'] ?? false) !== true) {
    header('Location: /art-gate.php', true, 303);
    exit;
}
$entries = require __DIR__ . '/art-common.php';
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>The Art of Being Unforgettable — La Davina Emilia</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"></head>
<body class="journal-page"><header class="survey-header"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">✦</span><span>La Davina Emilia</span></a><span>Private collection</span></header><main class="journal-shell"><section class="journal-intro"><p class="eyebrow">La Davina Emilia presents</p><h1>The Art of Being <em>Unforgettable.</em></h1><p>Three lessons on presence, standards, and knowing exactly when to leave them wanting more.</p></section><nav class="journal-nav" aria-label="Articles"><?php foreach ($entries as $slug => $entry): ?><a href="#<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($entry['title'], ENT_QUOTES, 'UTF-8') ?></a><?php endforeach; ?></nav><?php foreach ($entries as $slug => $entry): ?><article class="journal-entry" id="<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>"><header><p class="eyebrow"><?= htmlspecialchars($entry['eyebrow'], ENT_QUOTES, 'UTF-8') ?> <span aria-hidden="true">✦</span></p><h2><?= htmlspecialchars($entry['title'], ENT_QUOTES, 'UTF-8') ?></h2></header><div class="journal-prose"><?php foreach ($entry['paragraphs'] as $paragraph): ?><p><?= htmlspecialchars($paragraph, ENT_QUOTES, 'UTF-8') ?></p><?php endforeach; ?></div><section class="journal-comments" aria-labelledby="comment-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>"><p class="eyebrow" id="comment-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>">Leave a word</p><a class="tribute-inline" href="https://youpay.me/ladavinaemilia" target="_blank" rel="noreferrer"><span aria-hidden="true">✦</span><span>Before you leave a word, leave a little tribute for Emilia.</span><span aria-hidden="true">↗</span></a><form action="/art-comment-submit.php" method="post"><input name="entry" type="hidden" value="<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>"><label for="name-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>">What should Emilia call you?</label><input id="name-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>" name="name" type="text" maxlength="120" required><label for="comment-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>-body">Your comment</label><textarea id="comment-<?= htmlspecialchars($slug, ENT_QUOTES, 'UTF-8') ?>-body" name="comment" rows="5" maxlength="3000" required></textarea><button class="button button-primary" type="submit">Send your comment</button></form><p class="comment-note">Comments are reviewed by your Goddess before they appear here.</p></section></article><?php endforeach; ?></main></body></html>
