<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Frequently asked questions for La Davina Emilia."><title>FAQ — La Davina Emilia</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;1,500;1,600&family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"></head>
<body class="worship-page faq-page"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">✦</span><span>La Davina Emilia</span></a><nav aria-label="Primary navigation"><a href="/start-here.php">Start here</a><a href="/who-i-am.php">Who I am</a><a href="/rules.php">Rules</a><a href="/what-i-offer.php">What I Offer</a><a href="/ways-to-worship.php">Ways to Worship</a><a href="/kept-subs.php">Kept</a><a href="/journal-gate.php">Journal</a><a href="/faq.php" aria-current="page">FAQ</a><a class="nav-contact" href="/approach.php">Approach me</a></nav></header><main id="main" class="worship-shell"><article class="worship-letter faq-letter"><div class="worship-celestial" aria-hidden="true"><span class="worship-moon">☾</span><span class="worship-star worship-star-one">✦</span></div><header class="worship-intro"><p class="eyebrow">The things you ask</p><p class="worship-constellation" aria-hidden="true">✦&nbsp;✧&nbsp;✦</p><h1>Frequently <em>Asked.</em></h1></header><div class="faq-list">
<details open><summary>How do I start?</summary><p>Read the Rules, fill out the intake, send your first tribute, wait gracefully. That's the whole path. It's on the <a href="/start-here.php">Start Here</a> page in detail.</p></details>
<details><summary>How much should I tribute?</summary><p>I don't set minimums. A tribute is you telling me what I'm worth to you, and I'd rather hear your honest answer than my assigned one. That said: if your tribute wouldn't buy me a drink, don't insult us both by sending it.</p></details>
<details><summary>Do you do custom content?</summary><p>Yes, for men in my world who ask properly. Customs are priced individually based on what you're asking for. Ask me, describe it respectfully, and I'll tell you the tribute it requires.</p></details>
<details><summary>Do you offer sessions, sexting, or video calls?</summary><p>Yes, yes, and selectively. Sexting sessions, audio, tasks, and video calls are available to men I've vetted. New to me? The intake comes first. Everything comes after the intake.</p></details>
<details><summary>How often do you reply?</summary><p>I reply when I please, which is more often than you'd think and less often than you'd like. Kept Subs get priority, always. If you're waiting on a reply to a message that didn't include respect or a tribute, you may be waiting a while.</p></details>
<details><summary>What's the difference between a sender and a kept Sub?</summary><p>A sender tributes sometimes. A kept Sub belongs to me, consistently, and gets my consistency in return. Kept positions are limited and earned. Details are on the <a href="/kept-subs.php">Kept Subs</a> page.</p></details>
<details><summary>Do you do findom “draining”?</summary><p>I do what the dynamic calls for. Some men come to me to be emptied out and some come to be kept, built up, and held long-term. My intake asks which one you are. Both are valid. One of them gets more of my heart, and we both know which.</p></details>
<details><summary>I'm nervous and new. Is this for me?</summary><p>Some of my best boys walked in terrified. You don't need experience. You need honesty and good instructions. <a href="/start-here.php">Start Here</a> exists precisely for you.</p></details>
<details><summary>Do you ever meet Subs in person?</summary><p>Rarely, and only after a very long time, and never as a promise anyone can tribute toward. If we ever meet, it will be because I decided, and you'll know that's the truth.</p></details>
<details><summary>What if I disappoint you?</summary><p>Then you'll know. And you'll wish you didn't. I don't yell. I've never needed to. My disappointment is quieter: attention slows, warmth withdraws, and I decide when it has been earned again. If you want a consensually harsher dynamic, name that in your intake, including your limits. Cruelty without consent isn't power; it's just noise.</p><p>How you come back: you don't argue or send a wall of excuses. You acknowledge it briefly, behave well, and let me decide when you've earned warmth again. I don't hold grudges, but patterns teach us both something.</p></details>
<details><summary>I have a question that isn't here.</summary><p>Then ask it respectfully after you've read everything above. I answer what deserves answering.</p></details>
</div><section class="faq-contact"><p class="eyebrow">Contact / Approach</p><h2>Ask <em>properly.</em></h2><p>If you're new: read the Rules, fill out the intake, and let your answers introduce you. If you've completed it, wait gracefully. If you're an existing Sub, you know how to reach me. Business inquiries should use “Business” in the subject line and make the first sentence worth my time.</p><p>Whatever you write, write it like a man who's about to be evaluated by the most interesting woman he'll contact this year. Because you are.</p><a class="button button-primary" href="/approach.php">Approach Emilia <span aria-hidden="true">↗</span></a></section></article></main><footer class="site-footer"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">✦</span><span>La Davina Emilia</span></a><p>Be good. Be curious. Be memorable.</p><div class="social-links"><a href="/privacy.php">Privacy</a><a href="https://youpay.me/ladavinaemilia" target="_blank" rel="noreferrer">YouPay.Me</a></div><small>© 2026 La Davina Emilia. All rights reserved.</small></footer></body></html>
