<?php
declare(strict_types=1);

return [
    'stone-cathedral-below' => [
        'title' => 'The Stone Cathedral Below',
        'date' => 'Tulum',
        'eyebrow' => 'Journal entry #1',
        'paragraphs' => [
            'I got recertified to dive, and I want to be honest about why.',
            'Not for the fish. The fish are a bonus, and I’ll get to them. I did it because I needed to relearn a lesson I’d been teaching subs for years without ever putting my own body through it: you don’t get to skip the basics just because you think you’re already someone. My old certification had lapsed, and I could have done a “refresher.” Instead I sat through the whole thing, the theory, the skills, the pool work, the mask-clearing drills like a brand-new diver, because that’s the standard I hold everyone to and it would be embarrassing to hold myself to less. Turns out, relearning to breathe underwater from scratch is a very humbling, very useful thing for a goddess to do. I recommend it.',
            'Then Tulum. Then the cenotes.',
            'I don’t have words for the cenotes. I’m going to try anyway, because that’s the job. You descend through a hole in the jungle floor and the world goes completely, impossibly still. The water is so clear it looks like nothing, like air pretending to be a swimming pool. Light comes down in columns through the openings above, and the stalactites hang like the ceiling of a cathedral built by someone with no interest in being found. Cavern diving, the guides call it, meaning you’re always within sight of daylight, and I understand why. There’s a line you don’t cross in those places, a place where the light stops, and you feel the line even when nobody tells you where it is. I stayed on the good side of it. I’m a goddess, not an idiot.',
            'A few of the details I’ll keep forever:',
            'The silence. No fish sounds, no waves, no wind, nothing. Just your own breath in and out through the regulator, slow and even, the most meditative sound on earth. I went into a rhythm down there that I chase in pilates and never quite catch.',
            'The light. Swimming through a beam of sun in that water was the closest thing to flying I’ve ever done, and I rollerblade, so that’s saying something.',
            'The fish. In the cenotes, small and curious, unbothered by me, which I respect. Out on the reef, everything: a turtle gliding past like it had somewhere important to be, schools of fish moving as one organism, a barracuda hanging in the distance giving me a look, and a ray that lifted off the sand and flew. I swam the reef and felt like a guest in a kingdom far older and better run than anything up here.',
            'And the mermaid thing. Yes. I said it.',
            'There’s a specific joy, and I mean a specific joy, in being a heavily tattooed woman moving through turquoise water with her hair floating around her like ink. My black ink against the reef light. A gothic mermaid, which is what I called myself and what I will call myself for the rest of my life. I did slow underwater turns for no reason other than the pleasure of it. I floated on my back and looked up at the surface like a creature considering whether to go home at all. Some boys pay for the privilege of my attention; the ocean got it for free, and the ocean earned it.',
            'I came up from the last dive of the trip and sat on the boat with salt drying on my skin, and I thought about how I’d been teaching a lesson for years that I only learned down there: real power isn’t loud, it’s controlled. Buoyancy is control. Breathing is control. Knowing where the line is, and choosing, every second, to stay on the right side of it, is control.',
            'The reef doesn’t care that I’m a goddess either. But I think it liked me. 🖤',
        ],
    ],
    'jfk-first-class-lounge-rated' => [
        'title' => 'The JFK First Class Lounge, Rated',
        'date' => 'Queens, technically',
        'eyebrow' => 'Journal entry #2',
        'paragraphs' => [
            'I had a long layover, three hours, the kind where you’ve already eaten and the wifi is decent and the wine is free, which is to say: I had time, and I had material.',
            'So. Ratings. Hotness, out of 10, plus the imaginary job I assign to every stranger, because that’s what a goddess does when she’s bored, she profiles her fellow lounge guests like the world’s most glamorous HR department.',
            'Man #1, “The Deal.” 40s. Navy suit with no tie, which is a power move, and a watch that costs more than my first car. Reading something on paper, actual paper, which at this point is either arrogance or a flex, and honestly? Both work on me. He orders a coffee and a whiskey, at 11am. 7.5/10, and I want to be clear that I’m being stingy because he knows he’s handsome and I don’t reward confidence without content. Imaginary job: He buys failing family businesses, fixes them, and keeps the original staff. The suit is for the banks. The paper is a letter from a grandfather whose name is on a building.',
            'Man #2, “The Silver Fox.” 50s. Gray at the temples, tan in December, gold ring, linen shirt, the specific calm of a man who has never once been late in his life because people wait for him. He’s on a call, low voice, and I only caught one sentence and it was about a boat. 8/10, deducted one point for the shirt and one for the tan, and I’ll be honest, I’d have a drink with him just to find out what the boat is. Imaginary job: Restaurateur, three restaurants, all in different countries, all excellent. The tan is real and the call is about the boat he’s naming after his wife.',
            'Man #3, “The Architect.” Late 30s. Black turtleneck, black glasses, black coffee, black everything, reading something with diagrams. He has the hands of a man who draws. He glanced up exactly once, took in the room, filed it, returned to his page, which I respect enormously. 8/10, the turtleneck is doing a lot of the work and I’m at peace with that. Imaginary job: He designs museums, and one of his buildings is famous, and he’s never told a single person at a party that he designed it.',
            'The Twink. Early 20s. Designer luggage, immaculate skin, wearing what I believe is technically a scarf but functions as a whole personality. Ordered a rosé, at noon, correct. Told the bartender a story that made the bartender laugh so hard he stopped pouring. 9/10, the highest score I gave all day, and it wasn’t close, because the audacity of that scarf and the actual charisma underneath it is a combination I deeply respect. Imaginary job: Fashion publicist, obviously, but specifically the one who makes celebrities behave, and he’s terrifying at it.',
            'The Muscle Mommy. 30s. Athleisure that cost real money, the specific build of someone who deadlifts for joy, and a face like a knife. She ate a full protein-heavy meal while reading a book in a language I couldn’t identify and I loved her immediately. 9/10. Imaginary job: She’s a physiotherapist for a national team, and she could absolutely take any man in this lounge apart, and they all know it.',
            'The Other Goddess. 30s. Tattooed, like me, but in a completely different language, floral, bold, sleeved. Silk scarf, oversized sunglasses indoors, black coffee, sitting with perfect posture and the specific stillness of a woman who has decided how her morning is going. We made eye contact across the room, and there was an entire conversation in it, a mutual “yes, I see you, no, we don’t need to speak.” 10/10, no deductions, I’m not a hypocrite, and I’m rating her against myself and I came out even. Imaginary job: Heir to something. Nothing loud. She sits on the board of a family company she doesn’t run and doesn’t want to, and her real work is unknown to everyone in the room, including possibly the company.',
            'Final rankings: the other goddess and I tied for first, the twink and the muscle mommy tied for second, the three executives tied for a respectable third, and the entire lounge tied for last because the wine was mediocre and I am who I am.',
            'Three hours well spent. Next layover, I’m rating the pilots. 💋',
        ],
    ],
    'pages-on-my-arm' => [
        'title' => 'The Pages on My Arm',
        'date' => 'Wherever I am',
        'eyebrow' => 'Journal entry #6',
        'paragraphs' => [
            'Passport stamps used to be a thing. You’d hand over your little blue book and get stamped, a permanent mark of where you’d been, and I loved it the way I love anything that leaves evidence. Now most countries just scan you and wave you through, no ink, no proof, no souvenir. Efficient. Soul-less. Very modern.',
            'So I started stamping myself.',
            'My right forearm is my passport now, a growing collection of travel tattoos, one per place that changed me, chosen with more care than any souvenir shop ever could. This is the real one. The ink on the outside of me that matches the woman on the inside.',
            'Here’s the collection so far, in order of arrival:',
            'Salem, Massachusetts. Halloween. My first travel stamp, fittingly, and I got it in October with the whole town dressed up and witchy and cold and perfect. It’s a small, dark, old-fashioned piece, and it means: I go where the season is. I’ll be honest, Salem on Halloween is a tourist trap and I loved every single second of it, and I love that about myself.',
            'A scuba tank with a sugar skull. Mexico. For the recertification, the cenotes, the reef, all of it. The sugar skull is the Mexico part, obviously, and it’s the most me tattoo on my arm, a gothic mermaid’s badge. It means: I relearned how to breathe underwater and it changed how I breathe up here.',
            'A slice of key lime pie. Key West. No, I’m serious. A slice of key lime pie. It was the best thing I ate that entire trip, on a porch, in the heat, with the sun going down, and I decided right then that the tattoo would be the pie, and I have never once regretted it. It means: the small perfect pleasures count as much as the big dramatic ones. It’s also my favorite one to watch people react to. The confusion is delicious.',
            'A crowned fleur de lis. New Orleans. For the five days of creole and cajun, the beignets in my hair, the po’ boy on the street corner, the bread pudding that earned my silence. The crown, because New Orleans is royalty and I don’t think that’s a controversial statement. It means: some cities have presence the way some women do.',
            'A snail shell. Paris. For the escargot. I love escargot, I order it every time, and yes, the tattoo is a snail shell, because a snail shell is elegant and French and quietly funny if you know. It’s the newest, and it means: I stayed two weeks on a whim and pretended to be Belle with a sleeve and a rental car. It also means I have excellent taste and I’m secure enough to get a snail tattoo about it.',
            'And there’s more coming. There’s a list. There’s a whole itinerary in my head of places that have earned ink, and I won’t tell you all of them, because some of them I haven’t been to yet and I don’t spoil my own surprises.',
            'Here’s the thing about this project: people get tattoos of the places they went. I get tattoos of the places that worked on me. Every piece is a decision, and every decision is a little like the way I run my whole world: I don’t collect experiences, I keep them. Same as I keep my good boys. Same as I keep the things worth remembering.',
            'Some people leave their mark on the world.',
            'I have the world leave its mark on me, and then I decide which ones get to stay forever.',
            'My passport is running out of room. My arm is just getting started. 🖤',
        ],
    ],
    'destination-with-my-name-on-it' => [
        'title' => 'A Destination With My Name On It',
        'date' => 'New York',
        'eyebrow' => 'Journal entry #7',
        'paragraphs' => [
            'Here’s something I’ve never said out loud until now.',
            'New York is my home. And lately, it’s also just a destination.',
            'I want to be careful with that sentence, because I love this city with something close to violence. I love the bodega guys who’ve watched me change my hair six times. I love knowing which train car to stand in. I love the specific New York winter light that makes everyone’s face look like a film still. Home is home. I’m not renouncing anything.',
            'But I travel monthly now, and something happened that I didn’t expect. Coming back started feeling like arriving. The way it feels when you land somewhere for a trip, that first taxi ride, the “oh, right, this place.” And I noticed it the way you’d notice a tooth that’s slightly loose. You don’t panic. You just keep touching it with your tongue and thinking about it.',
            'And the timing is funny, because everyone I know started leaving.',
            'My friends are in Lisbon now. Some in Mexico City. One in Thailand, one in Bali, a couple in Spain, people I used to see for dinner every month scattered across time zones like a constellation I have to squint at to find. I get it. I’ve watched them go and felt zero judgment, only a kind of recognition, the feeling of watching someone do something you’ve already started thinking about doing. They left first. I noticed. That’s all.',
            'And then the jungle did the rest.',
            'Because here’s what the Mexico condo taught me: I don’t actually know how much of my life is a choice and how much is just habit. I lived in New York because I always had. Because it’s the default for a woman like me, ambitious, creative, in the content world, “of course she’s in New York.” But I bought a home in another country on a whim and it fit like a ring I’d owned forever. So the question stopped being “why would I leave New York” and became the more honest one: “why would I stay in one place at all, when every month I go somewhere and feel more myself than I do walking the same three blocks?”',
            'So. I think it’s time.',
            'I’m not announcing a move with a countdown and boxes, because that’s not how I do things. I do things the way I bought the condo, quietly, completely, and all at once when nobody’s looking. What I’ll say is: I’m looking. At places. With intention now, instead of curiosity. A base that isn’t a habit. Somewhere the light is better and the cost of living isn’t a personality test. Somewhere I could put down the same roots I have here, but chosen this time, instead of inherited.',
            'New York, you gave me everything and I’ll never pretend otherwise. But you raised a woman who now knows how to live anywhere, and that woman owes it to herself to prove it.',
            'Consider this the soft announcement. The hard one will come when there’s a key in my hand in a city you don’t know yet. 💋',
        ],
    ],
];
