<?php
declare(strict_types=1);

return [
    'name_pronouns' => 'Your name / what I should call you and pronouns:',
    'age_location_timezone' => 'Age / Location / time zone:',
    'how_found' => 'How did you find me?',
    'experience' => 'Are you new to submission, kink, findom or experienced? Tell me your history.',
    'relationship_type' => 'Are you looking for a one-time tribute, an ongoing dynamic, or something in between?',
    'contact_and_send_frequency' => 'How often do you want to hear from me, and how often do you realistically want to send?',
    'good_means' => 'What does being a “good boy” or “good girl” mean to you?',
    'desired_dynamic' => 'What kind of dynamic do you want with me? (Casual, committed, daily, occasional, etc.)',
    'six_month_fantasy' => 'What does your fantasy version of us look like six months from now?',
    'when_good' => 'What do you want me to do when you’re good?',
    'when_disappointing' => 'What do you want me to do when you disappoint me?',
    'interests_ranked' => 'Are you looking for praise, guilt, denial, tasks, worship, roleplay, or a mix? Rank them.',
    'hard_limits' => 'Hard limits: What is absolutely off the table, always? (Nothing here is judged. Everything here is respected.)',
    'soft_limits' => 'Soft limits: What are you unsure about, curious about, or willing to explore with the right person?',
    'humiliation' => 'Is humiliation on the table at all? If yes, what kind, and what would go too far?',
    'waiting' => 'Are you okay with being told no, ignored, or made to wait? (For some Subs this is the whole thrill. For others it’s a dealbreaker.)',
    'aftercare' => 'How do you want me to handle it if we cross a line or something goes wrong? What’s your aftercare like, if you want any at all?',
    'nervous_to_share' => 'Is there anything you’re nervous about telling me? Say it here. I’d rather know now.',
    'contact_method' => 'What’s the best way to reach you, and when?',
    'privacy' => 'Are you private about this side of your life, or open?',
    'domme_dealbreakers' => 'What are your dealbreakers in a domme? What would make you walk away?',
    'loyalty' => 'What makes you feel most loyal to someone? What keeps you coming back?',
    'monthly_budget' => 'What is your realistic monthly tribute budget? (Be honest. I’d rather have a real number than a fantasy one.)',
    'payment_method' => 'Do you prefer to send by Zelle, Throne, or another method?',
    'sending_preference' => 'Do you want to be told exactly when and how much to send, or do you prefer to send spontaneously?',
    'drained_or_kept' => 'How do you feel about being drained versus being kept? Which do you want from me?',
    'arrangement' => 'Would you like a formal arrangement, a casual send-when-you-can relationship, or something you haven’t figured out yet?',
    'financial_hardship' => 'Have you ever gone into debt or financial hardship for Findom? (If yes, we will talk about this before anything else. I take care of my Subs. I don’t ruin them.)',
    'why_pick_you' => 'In one paragraph: why should I pick you?',
    'first_send' => 'What’s the first thing you’d send me, and why?',
    'finish_sentence' => 'Finish this sentence: “I want to be good for you because…”',
    'questions_for_emilia' => 'Do you have any questions for me? I promise you can ask me anything.',
];
